### PR TITLE
ADD css & assets watch mode for rebundle & livereload. Fixes atomify-css#24

### PR DESCRIPTION
**Pull request by serapath**

### CODE REVIEW

**Comment by serapath** [comment]
hi conradz, it has been a while and i was pretty busy with lots of stuff, but now i'm returning.
I forked `rework-npm` in order to create a pull request.

I'm not so much in the code yet - from what I am able to decipher, i would replace setting an array property on the module.exports of `rework-assets` with... ...a callback passed to `rework-assets`, right? How does that again affect `rework-npm`?

**Comment by conradz** [comment]
Sorry for the huge delay, been away for a while and have been catching up.

I'm fine with the current code in this PR, does it satisfy your requirements? If so, I'll merge and cut a new release. I'm not following on how this all relates to rework-npm, I may be missing exactly what you want to do.

**Comment by serapath** [comment]
yes, it satisfies them :-)

**Comment by conradz** [comment]
Version 1.1.0 released with `onFile` option included!

**Comment by serapath** [comment]
yay, awesome :-) thx

**Pull request merged**
